name: bookly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
